DGC test data from Belgium
eu-digital-green-certificates/dgc-testdata pull request #140
Opened 2021-05-19 15:05 UTC by ortwin45

2021-05-19 16:33 UTC, SchulzeStTSI commented
@ortwin45 Can you please check your date values. The are not correctly formatted. "validationClockInstant" is as well not properly formatted.

2021-05-19 16:37 UTC, SchulzeStTSI requested changes
Please correct the JSONs and the date times.

2021-05-19 18:37 UTC, ortwin45 commented
Datetime formatting has been fixed. Can you verify again? 
Thanks!

2021-05-20 12:09 UTC, SchulzeStTSI approved these changes

2021-05-20 12:09 UTC, merged